### ISSUE TITLE
Fix rotating logo - image needs to be exactly square or it doesn't rotate around the center of the circle

### ISSUE THREAD

**Issue by Abibubble** [vanessacleary/W-I-T-IT-LAB-Breast-Cancer-Awareness#50]

**Comment by auxfuse** [comment]
We actually had a chat about this right after you left. Might be a good idea to not have it on constant rotate, maybe a slight rotate effect on hover. 😃

**Comment by Abibubble** [comment]
Cool, I like that plan. However, the image will still need to be square, otherwise we'll have a mad amount of CSS to do to get it to rotate properly

**Comment by vanessacleary** [comment]
Done
